# Docker Compose file for a multi-container application with backend and frontend services
services:
  backend:
    image: backend:v1
    environment:
      - PROD_PORT=${PROD_PORT}
      - MONGO_URL=${MONGO_URL}
      - SECRET_KEY=${SECRET_KEY}
    restart: always
    networks:
      - app-network
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:${PROD_PORT:-8081}/api/ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: frontend:v1
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3001:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: always
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:80"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  app-network:
