# Docker Compose file for a multi-container application with backend, frontend, and proxy services
services:
  backend:
    image: backend:v1
    environment:
      - PROD_PORT=${PROD_PORT}
      - MONGO_URL=${MONGO_URL}
      - SECRET_KEY=${SECRET_KEY}
    restart: always
    networks:
      - app-network
    # no ports exposed here

  frontend:
    image: frontend:v1
    environment:
      - VITE_API_URL=${VITE_API_URL}
    ports:
      - "3001:80"
    depends_on:
      - backend
      - proxy
    restart: always
    networks:
      - app-network

  proxy:
    image: nginx:alpine
    restart: always
    depends_on:
      - backend
    networks:
      - app-network
    ports:
      - "8081:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

networks:
  app-network:
